force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Created_By__c.field-meta.xml
<CustomField>
    <fullName>Created_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Created_By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Last_Modified_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last_Modified_By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Invoices2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Merchandise__c/Merchandise__c.object-meta.xml
<CustomObject>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchandise__c/fields/Created_By__c.field-meta.xml
<CustomField>
    <fullName>Created_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Created_By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merchandise</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Merchandise__c/fields/Last_Modified_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last_Modified_By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merchandise1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Merchandise__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merchandise2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestCreateinvoice.cls
@IsTest
public class TestCreateinvoice {
    static testMethod void Createinvoice(){
        Merchandise__c m= new Merchandise__c();
        Invoice__c i = new Invoice__c();
        m.Name= 'Lappy';
        m.Owner__c='005o0000000EV0j';
            m.Last_Modified_By__c ='005o0000000EV0j';
            m.Created_By__c='005o0000000EV0j';
            m.Price__c=100;
            m.Quantity__c=2;
        insert m;
        
        System.assertEquals('Open',i.Status__c);
            
        
        
    }

}